#!/usr/bin/env bash
#This script installs nginx
# Install nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
# Configure nginx to listen on port 80 and serve "Holberton School for the win!" at the root
sudo bash -c 'echo "Holberton School for the win!" > /var/www/html/index.html'

# Restart nginx
sudo service nginx restart
